# .github/workflows/deploy.yml

# ... (keep the top part of the file as is)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    
    # Add these two lines
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
